services:
  - type: web
    name: hackrx-api
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_REQUESTS_PER_MINUTE
        value: 10
      - key: QUESTION_PROCESSING_DELAY
        value: 8
      - key: MAX_RETRIES
        value: 3
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
    disk:
      name: hackrx-disk
      mountPath: /tmp
      sizeGB: 1
